### ISSUE TITLE
Converting Raw UVG data into mkv

### ISSUE THREAD

**Issue by architachoudhary** [tukilabs/Video-Compression-Net#3]
.

**Comment by prasangadhungel** [comment]
Hi Archita,

Following script will help you to covert UVG data into mkv using ffmpeg:
```ffmpeg -y -pix_fmt yuv420p -s WxH -r Frame_rate -i Filename.yuv output.mkv```

If you want the converted data to be compressed using H.264 or H.265, you can use ` -c:v libx265` or ` -c:v libx264`. 
You can also refer to our scripts [here](https://github.com/tukilabs/Video-Compression-Net/tree/master/evaluation).

Best,
Prasanga Dhungel
