### ISSUE TITLE
I want H.264 vompression evaluation benchmark values 

### ISSUE THREAD

**Issue by durgabhavaniv** [tukilabs/Video-Compression-Net#4]
Is that possible to get compression images with traditional h.264 compression and I want to evaluate those results like finding PSNR and MS-SSIM as shown in [https://arxiv.org/pdf/1812.00101.pdf](https://arxiv.org/pdf/1812.00101.pdf) this paper benchmark results.

**Comment by prasangadhungel** [comment]
Hi @durgabhavaniv ,

We have mentioned the link to our experimental results in the [experiment](https://github.com/tukilabs/Video-Compression-Net/tree/master/evaluation) section. In case you haven't checked, [here](https://drive.google.com/drive/folders/1R-jnkocZ2Xe-tCq99gcmm1Nr8bvCaTCk?usp=sharing) it is. It contains the original UVG dataset, and the frames compressed using h.264, h.265 and ours. PS: We cannot share the JCT-VC dataset for the copyright issues.

Best wishes,
Prasanga Dhungel

**Comment by durgabhavaniv** [comment]
hi @PrasangaDhungel 

Thanks for update, Actually I want to compress images with h.264 by my self using traditional compression technique, similar to compress.py proposed here. Is that possible ?

Thank you.

**Comment by prasangadhungel** [comment]
Hi @durgabhavaniv 

Yes, the compression is possible but first you have to convert the video into raw frames. FFmpeg can be of great help on this, or you can simply use our [conversion script](https://github.com/tukilabs/Video-Compression-Net/blob/master/evaluation/extract_png.sh). After that, you can compressed the extracted raw pngs using the compress.py. You can check our own evaluation [here](https://github.com/tukilabs/Video-Compression-Net/blob/master/evaluation/UVG_Eval.ipynb)

Best,
Prasanga
