### ISSUE TITLE
Regularization for optical flow values?

### ISSUE THREAD

**Issue by heydarshahi** [tukilabs/Video-Compression-Net#5]
Hi! 

Did you use any regularization for optical flow values? I'm trying to train the model end-to-end but optical flow values get arbitrarily large. I wonder if you've faced a similar problem.

Thanks!

Amin

**Comment by prasangadhungel** [comment]
Hi Heydarshahi!

We also trained the model end-to-end. However, it is difficult to train all the components at once. So, what we did was, we first trained the optical flow component alone. Then we used this weight in the optical flow component of the video compression pipeline without freezing it. That means the optical flow component is still trained in the end-to-end setting.

For your reference, [Here](https://github.com/tukilabs/Video-Compression-Net/blob/master/opticalflowtrain.py) is the code to train the optical flow component only.

Regards,
Prasanga

**Comment by heydarshahi** [comment]
Thanks for the explanation, Prasanga!
